# Generated by Django 3.0.6 on 2020-05-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slam',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='slam',
            name='weakness',
        ),
    ]
